application:
  name: socket-io-echo
  project: socket-io-echo-server
  cloud_region: aws/eu-west-3
  publicly_accessible: true
routers:
- name: main
  routes:
  - application_name: socket-io-echo
    paths:
    - /