application:
  name: socket-io-echo
  project: opensource
  cloud_region: aws/us-west-2
  publicly_accessible: true
routers:
- name: main
  routes:
  - application_name: socket-io-echo
    paths:
    - /